# Management
server:
  port: 8083
  servlet.context-path: /spring-boot-security-custom-login-page/
endpoints:
  hawtio:
    enabled: true
  jolokia:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, hawtio, env
      base-path: /monitoring      
  endpoint:
    health:
      show-details: always
info:
  app:
    spring-boot-security-custom-login-page
    description:This is a microservice for springboot application testing
          
## Application Name
camel:
  springboot:
    name: spring-boot-security-custom-login-page
#spring.datasource.url: jdbc:mysql://localhost:3306/logindb
#spring.datasource.username: root
#spring.datasource.password: Arm@12345
#spring.datasource.platform: mysql

spring.datasource.url: jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username: QDE_TEST
spring.datasource.password: ORACLE



spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

